apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check
  labels:
    app: health-check
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-check
  template:
    metadata:
      labels:
        app: health-check 
    spec:
      containers:
      - name: health-check
        image: esiee79798987/health-check:latest
        ports:
        - containerPort: 5000
        env:
        - name: URL_TO_CHECK
          value: "http://schoodle-api:5000"